// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLvizSyskt32RHAADd0FyeL7Bthva9gU8',
    appId: '1:62351942822:web:1266b0f2b61dca99c48067',
    messagingSenderId: '62351942822',
    projectId: 'music-spotify-clone-78c1a',
    authDomain: 'music-spotify-clone-78c1a.firebaseapp.com',
    storageBucket: 'music-spotify-clone-78c1a.firebasestorage.app',
    measurementId: 'G-WT6DWWWKSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC8H94npjHOF88IUvUSg72B8UtIBLYbjM',
    appId: '1:62351942822:android:32cf4e477e09f46fc48067',
    messagingSenderId: '62351942822',
    projectId: 'music-spotify-clone-78c1a',
    storageBucket: 'music-spotify-clone-78c1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqn0NwbTCpgl7KTRqp2vDPuEIFGsnuz-A',
    appId: '1:62351942822:ios:701ea8c8fc1538d0c48067',
    messagingSenderId: '62351942822',
    projectId: 'music-spotify-clone-78c1a',
    storageBucket: 'music-spotify-clone-78c1a.firebasestorage.app',
    iosBundleId: 'com.example.musicClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqn0NwbTCpgl7KTRqp2vDPuEIFGsnuz-A',
    appId: '1:62351942822:ios:701ea8c8fc1538d0c48067',
    messagingSenderId: '62351942822',
    projectId: 'music-spotify-clone-78c1a',
    storageBucket: 'music-spotify-clone-78c1a.firebasestorage.app',
    iosBundleId: 'com.example.musicClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLvizSyskt32RHAADd0FyeL7Bthva9gU8',
    appId: '1:62351942822:web:36ce1c84f9f8a354c48067',
    messagingSenderId: '62351942822',
    projectId: 'music-spotify-clone-78c1a',
    authDomain: 'music-spotify-clone-78c1a.firebaseapp.com',
    storageBucket: 'music-spotify-clone-78c1a.firebasestorage.app',
    measurementId: 'G-KHH2CV8Q9E',
  );
}
